server:
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  thymeleaf:
    cache: true

hmrc:
  api:
    base-url: https://api.service.hmrc.gov.uk

logging:
  level:
    com.mtdsubmitter: INFO
    org.hibernate.SQL: WARN
